### ISSUE TITLE
Autograding not working

### ISSUE THREAD

**Issue by websi96** [TU-Wien-dataLAB/Grader-Service#18]
**Describe the bug**
The Helm Chart has no option to select the autograder used.
Grading doesn't work because of missing volume mounts.

**To Reproduce**
1. deploy examples from helmchart
2. try to grade something

**Expected behavior**
should grade notebooks

**Comment by websi96** [comment]
I already started to make changes for this.

**Comment by websi96** [comment]
It fails on first grading submission:

```
ERROR 2022-09-09 08:39:31,027 local_grader \| Failed autograding job for submission 1 in KubeAutogradeExecutor
--
Fri, Sep 9 2022 10:39:31 am | Traceback (most recent call last):
Fri, Sep 9 2022 10:39:31 am | File "/usr/local/lib/python3.8/dist-packages/grader_service/autograding/local_grader.py", line 89, in start
Fri, Sep 9 2022 10:39:31 am | await self._run()
Fri, Sep 9 2022 10:39:31 am | File "/usr/local/lib/python3.8/dist-packages/grader_service/autograding/kube/kube_grader.py", line 172, in _run
Fri, Sep 9 2022 10:39:31 am | os.mkdir(self.output_path)
Fri, Sep 9 2022 10:39:31 am | FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/grader-service/convert_out/submission_1'
Fri, Sep 9 2022 10:39:31 am | INFO 2022-09-09 08:39:31,201 grading \| Autograding task of submission 1 exited!
```

I guess /var/lib/grader-service/convert_out is not there initially and os.mkdir(self.output_path) can't create subdirectories if the parent doesn't exist. See: https://www.javatpoint.com/linux-mkdir-p

**Comment by websi96** [comment]
If this directory then exists the kubespawner hangs indefinatly without any error:

```
INFO 2022-09-09 08:42:32,694 kube_grader | Starting pod 132291417d603eb2c284b0369231d9f0ee817625 with command: grader-convert autograde -i "/var/lib/grader-service/convert_in/submission_1" -o "/var/lib/grader-service/convert_out/submission_1" -p "*.ipynb" --log-level=INFO
```

**Comment by websi96** [comment]
Error on line [160 in kube_grader.py](https://github.com/TU-Wien-dataLAB/Grader-Service/blob/main/grader_service/grader_service/autograding/kube/kube_grader.py#L160)!

I would like to see the log output of[ line 105](https://github.com/TU-Wien-dataLAB/Grader-Service/blob/main/grader_service/grader_service/autograding/kube/kube_grader.py#L105) to see if the kubeconfig gets loaded properly.

```
ERROR 2022-09-09 14:37:01,197 kube_grader \| Kubernetes client could not connect to cluster! Is it running and specified correctly?
--
Fri, Sep 9 2022 4:37:01 pm | ERROR 2022-09-09 14:37:01,198 local_grader \| Failed autograding job for submission 1 in KubeAutogradeExecutor
Fri, Sep 9 2022 4:37:01 pm | Traceback (most recent call last):
Fri, Sep 9 2022 4:37:01 pm | File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 174, in _new_conn
Fri, Sep 9 2022 4:37:01 pm | conn = connection.create_connection(
Fri, Sep 9 2022 4:37:01 pm | File "/usr/local/lib/python3.8/dist-packages/urllib3/util/connection.py", line 95, in create_connection
Fri, Sep 9 2022 4:37:01 pm | raise err
Fri, Sep 9 2022 4:37:01 pm | File "/usr/local/lib/python3.8/dist-packages/urllib3/util/connection.py", line 85, in create_connection
Fri, Sep 9 2022 4:37:01 pm | sock.connect(sa)
Fri, Sep 9 2022 4:37:01 pm | TimeoutError: [Errno 110] Connection timed out
Fri, Sep 9 2022 4:37:01 pm |  
Fri, Sep 9 2022 4:37:01 pm | During handling of the above exception, another exception occurred:
Fri, Sep 9 2022 4:37:01 pm |  
Fri, Sep 9 2022 4:37:01 pm | Traceback (most recent call last):
Fri, Sep 9 2022 4:37:01 pm | File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 703, in urlopen
Fri, Sep 9 2022 4:37:01 pm | httplib_response = self._make_request(
Fri, Sep 9 2022 4:37:01 pm | File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 386, in _make_request
Fri, Sep 9 2022 4:37:01 pm | self._validate_conn(conn)
Fri, Sep 9 2022 4:37:01 pm | File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
Fri, Sep 9 2022 4:37:01 pm | conn.connect()
Fri, Sep 9 2022 4:37:01 pm | File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 358, in connect
Fri, Sep 9 2022 4:37:01 pm | self.sock = conn = self._new_conn()
Fri, Sep 9 2022 4:37:01 pm | File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 186, in _new_conn
Fri, Sep 9 2022 4:37:01 pm | raise NewConnectionError(
Fri, Sep 9 2022 4:37:01 pm | urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fa2d9e88910>: Failed to establish a new connection: [Errno 110] Connection timed out
Fri, Sep 9 2022 4:37:01 pm |  
Fri, Sep 9 2022 4:37:01 pm | During handling of the above exception, another exception occurred:
Fri, Sep 9 2022 4:37:01 pm |  
Fri, Sep 9 2022 4:37:01 pm | Traceback (most recent call last):
Fri, Sep 9 2022 4:37:01 pm | File "/usr/local/lib/python3.8/dist-packages/grader_service/autograding/kube/kube_grader.py", line 177, in _run
Fri, Sep 9 2022 4:37:01 pm | grader_pod = self.start_pod()
Fri, Sep 9 2022 4:37:01 pm | File "/usr/local/lib/python3.8/dist-packages/grader_service/autograding/kube/kube_grader.py", line 160, in start_pod
Fri, Sep 9 2022 4:37:01 pm | pod = self.client.create_namespaced_pod(namespace=self.namespace, body=pod)
Fri, Sep 9 2022 4:37:01 pm | File "/usr/local/lib/python3.8/dist-packages/kubernetes/client/api/core_v1_api.py", line 7356, in create_namespaced_pod
Fri, Sep 9 2022 4:37:01 pm | return self.create_namespaced_pod_with_http_info(namespace, body, **kwargs) # noqa: E501
Fri, Sep 9 2022 4:37:01 pm | File "/usr/local/lib/python3.8/dist-packages/kubernetes/client/api/core_v1_api.py", line 7455, in create_namespaced_pod_with_http_info
Fri, Sep 9 2022 4:37:01 pm | return self.api_client.call_api(
Fri, Sep 9 2022 4:37:01 pm | File "/usr/local/lib/python3.8/dist-packages/kubernetes/client/api_client.py", line 348, in call_api
Fri, Sep 9 2022 4:37:01 pm | return self.__call_api(resource_path, method,
Fri, Sep 9 2022 4:37:01 pm | File "/usr/local/lib/python3.8/dist-packages/kubernetes/client/api_client.py", line 180, in __call_api
Fri, Sep 9 2022 4:37:01 pm | response_data = self.request(
Fri, Sep 9 2022 4:37:01 pm | File "/usr/local/lib/python3.8/dist-packages/kubernetes/client/api_client.py", line 391, in request
Fri, Sep 9 2022 4:37:01 pm | return self.rest_client.POST(url,
Fri, Sep 9 2022 4:37:01 pm | File "/usr/local/lib/python3.8/dist-packages/kubernetes/client/rest.py", line 275, in POST
Fri, Sep 9 2022 4:37:01 pm | return self.request("POST", url,
Fri, Sep 9 2022 4:37:01 pm | File "/usr/local/lib/python3.8/dist-packages/kubernetes/client/rest.py", line 168, in request
Fri, Sep 9 2022 4:37:01 pm | r = self.pool_manager.request(
Fri, Sep 9 2022 4:37:01 pm | File "/usr/local/lib/python3.8/dist-packages/urllib3/request.py", line 78, in request
Fri, Sep 9 2022 4:37:01 pm | return self.request_encode_body(
Fri, Sep 9 2022 4:37:01 pm | File "/usr/local/lib/python3.8/dist-packages/urllib3/request.py", line 170, in request_encode_body
Fri, Sep 9 2022 4:37:01 pm | return self.urlopen(method, url, **extra_kw)
Fri, Sep 9 2022 4:37:01 pm | File "/usr/local/lib/python3.8/dist-packages/urllib3/poolmanager.py", line 376, in urlopen
Fri, Sep 9 2022 4:37:01 pm | response = conn.urlopen(method, u.request_uri, **kw)
Fri, Sep 9 2022 4:37:01 pm | File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 815, in urlopen
Fri, Sep 9 2022 4:37:01 pm | return self.urlopen(
Fri, Sep 9 2022 4:37:01 pm | File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 815, in urlopen
Fri, Sep 9 2022 4:37:01 pm | return self.urlopen(
Fri, Sep 9 2022 4:37:01 pm | File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 815, in urlopen
Fri, Sep 9 2022 4:37:01 pm | return self.urlopen(
Fri, Sep 9 2022 4:37:01 pm | File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 787, in urlopen
Fri, Sep 9 2022 4:37:01 pm | retries = retries.increment(
Fri, Sep 9 2022 4:37:01 pm | File "/usr/local/lib/python3.8/dist-packages/urllib3/util/retry.py", line 592, in increment
Fri, Sep 9 2022 4:37:01 pm | raise MaxRetryError(_pool, url, error or ResponseError(cause))
Fri, Sep 9 2022 4:37:01 pm | urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='10.43.0.1', port=443): Max retries exceeded with url: /api/v1/namespaces/grader/pods (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fa2d9e88910>: Failed to establish a new connection: [Errno 110] Connection timed out'))
Fri, Sep 9 2022 4:37:01 pm |  
Fri, Sep 9 2022 4:37:01 pm | During handling of the above exception, another exception occurred:
Fri, Sep 9 2022 4:37:01 pm |  
Fri, Sep 9 2022 4:37:01 pm | Traceback (most recent call last):
Fri, Sep 9 2022 4:37:01 pm | File "/usr/local/lib/python3.8/dist-packages/grader_service/autograding/local_grader.py", line 89, in start
Fri, Sep 9 2022 4:37:01 pm | await self._run()
Fri, Sep 9 2022 4:37:01 pm | File "/usr/local/lib/python3.8/dist-packages/grader_service/autograding/kube/kube_grader.py", line 201, in _run
Fri, Sep 9 2022 4:37:01 pm | raise RuntimeError("Pod has failed execution!")
Fri, Sep 9 2022 4:37:01 pm | RuntimeError: Pod has failed execution!
Fri, Sep 9 2022 4:37:01 pm | INFO 2022-09-09 14:37:01,395 grading \| Autograding task of submission 1 exited!
```

**Comment by websi96** [comment]
```
ERROR 2022-09-09 16:47:45,737 local_grader \| Failed autograding job for submission 1 in KubeAutogradeExecutor
--
Fri, Sep 9 2022 6:47:45 pm | Traceback (most recent call last):
Fri, Sep 9 2022 6:47:45 pm | File "/usr/local/lib/python3.8/dist-packages/grader_service/autograding/local_grader.py", line 90, in start
Fri, Sep 9 2022 6:47:45 pm | await self._run()
Fri, Sep 9 2022 6:47:45 pm | File "/usr/local/lib/python3.8/dist-packages/grader_service/autograding/kube/kube_grader.py", line 180, in _run
Fri, Sep 9 2022 6:47:45 pm | grader_pod = self.start_pod()
Fri, Sep 9 2022 6:47:45 pm | File "/usr/local/lib/python3.8/dist-packages/grader_service/autograding/kube/kube_grader.py", line 162, in start_pod
Fri, Sep 9 2022 6:47:45 pm | pod = self.client.create_namespaced_pod(namespace=self.namespace, body=pod)
Fri, Sep 9 2022 6:47:45 pm | File "/usr/local/lib/python3.8/dist-packages/kubernetes/client/api/core_v1_api.py", line 7356, in create_namespaced_pod
Fri, Sep 9 2022 6:47:45 pm | return self.create_namespaced_pod_with_http_info(namespace, body, **kwargs) # noqa: E501
Fri, Sep 9 2022 6:47:45 pm | File "/usr/local/lib/python3.8/dist-packages/kubernetes/client/api/core_v1_api.py", line 7455, in create_namespaced_pod_with_http_info
Fri, Sep 9 2022 6:47:45 pm | return self.api_client.call_api(
Fri, Sep 9 2022 6:47:45 pm | File "/usr/local/lib/python3.8/dist-packages/kubernetes/client/api_client.py", line 348, in call_api
Fri, Sep 9 2022 6:47:45 pm | return self.__call_api(resource_path, method,
Fri, Sep 9 2022 6:47:45 pm | File "/usr/local/lib/python3.8/dist-packages/kubernetes/client/api_client.py", line 170, in __call_api
Fri, Sep 9 2022 6:47:45 pm | body = self.sanitize_for_serialization(body)
Fri, Sep 9 2022 6:47:45 pm | File "/usr/local/lib/python3.8/dist-packages/kubernetes/client/api_client.py", line 241, in sanitize_for_serialization
Fri, Sep 9 2022 6:47:45 pm | return {key: self.sanitize_for_serialization(val)
Fri, Sep 9 2022 6:47:45 pm | File "/usr/local/lib/python3.8/dist-packages/kubernetes/client/api_client.py", line 241, in <dictcomp>
Fri, Sep 9 2022 6:47:45 pm | return {key: self.sanitize_for_serialization(val)
Fri, Sep 9 2022 6:47:45 pm | File "/usr/local/lib/python3.8/dist-packages/kubernetes/client/api_client.py", line 241, in sanitize_for_serialization
Fri, Sep 9 2022 6:47:45 pm | return {key: self.sanitize_for_serialization(val)
Fri, Sep 9 2022 6:47:45 pm | File "/usr/local/lib/python3.8/dist-packages/kubernetes/client/api_client.py", line 241, in <dictcomp>
Fri, Sep 9 2022 6:47:45 pm | return {key: self.sanitize_for_serialization(val)
Fri, Sep 9 2022 6:47:45 pm | File "/usr/local/lib/python3.8/dist-packages/kubernetes/client/api_client.py", line 221, in sanitize_for_serialization
Fri, Sep 9 2022 6:47:45 pm | return [self.sanitize_for_serialization(sub_obj)
Fri, Sep 9 2022 6:47:45 pm | File "/usr/local/lib/python3.8/dist-packages/kubernetes/client/api_client.py", line 221, in <listcomp>
Fri, Sep 9 2022 6:47:45 pm | return [self.sanitize_for_serialization(sub_obj)
Fri, Sep 9 2022 6:47:45 pm | File "/usr/local/lib/python3.8/dist-packages/kubernetes/client/api_client.py", line 241, in sanitize_for_serialization
Fri, Sep 9 2022 6:47:45 pm | return {key: self.sanitize_for_serialization(val)
Fri, Sep 9 2022 6:47:45 pm | File "/usr/local/lib/python3.8/dist-packages/kubernetes/client/api_client.py", line 241, in <dictcomp>
Fri, Sep 9 2022 6:47:45 pm | return {key: self.sanitize_for_serialization(val)
Fri, Sep 9 2022 6:47:45 pm | File "/usr/local/lib/python3.8/dist-packages/kubernetes/client/api_client.py", line 238, in sanitize_for_serialization
Fri, Sep 9 2022 6:47:45 pm | for attr, _ in six.iteritems(obj.openapi_types)
Fri, Sep 9 2022 6:47:45 pm | AttributeError: 'property' object has no attribute 'openapi_types'
Fri, Sep 9 2022 6:47:45 pm | INFO 2022-09-09 16:47:45,877 grading \| Autograding task of submission 1 exited!
```
