### ISSUE TITLE
Git push fails on release assignment

### ISSUE THREAD

**Issue by adammccartney** [TU-Wien-dataLAB/Grader-Service#93]
**Describe the bug**

On local development setup, `user1` creates assignment `1` within `lect1`. Upon completing the desired chages, `user1` tries to release the assignment.

On release assignment, grader service tries a `git push`, this command fails.
+ The assignment table in the database is updated to show "status: pushed"
+ The git repository retains no record of this push. 

**To Reproduce**

Checkout tip of "migration to jupyter 4" branch to a new local branch 
`git checkout -b local/migration+router 194551f94dac37184ca7a1d03aa6bc6c619b4c0e`

Merge changes from the "92 using react router" branch 
`git merge d00b97a518f70ff165ba66e46f9f85ad36baf272`

+ Prepare dev install 
+ create a fresh db 
+ migrate the database 
+ run jupyterhub and grader service
+ create new assignment 
+ click release assignment 
+ enter commit message

**Expected behavior**
+ Grader Service updates the database and manages to successfully push 

**Screenshots**

jupyter hub logs:

```conf
[I 2023-07-14 09:47:17.581 ServerApp] http://127.0.0.1:4010/services/grader/lectures/1
[I 2023-07-14 09:47:17.613 ServerApp] http://127.0.0.1:4010/services/grader/lectures/1/assignments/1
[I 2023-07-14 09:47:17.652 ServerApp] Deleting files in release directory
[I 2023-07-14 09:47:17.653 ServerApp] Starting GenerateAssignment converter
[I 2023-07-14 09:47:17.656 ServerApp] Converting notebook /home/adam/Code/tuw/datalab/lab_dir/user1/source/lect1/1/Untitled.ipynb
[I 2023-07-14 09:47:17.771 ServerApp] Writing 1371 bytes to /home/adam/Code/tuw/datalab/lab_dir/user1/release/lect1/1/gradebook.json
[I 2023-07-14 09:47:17.889 ServerApp] Writing 1739 bytes to /home/adam/Code/tuw/datalab/lab_dir/user1/release/lect1/1/Untitled.ipynb
[I 2023-07-14 09:47:17.889 ServerApp] Setting destination file permissions to 664
[I 2023-07-14 09:47:17.890 ServerApp] Reading 1371 bytes from /home/adam/Code/tuw/datalab/lab_dir/user1/release/lect1/1/gradebook.json
[I 2023-07-14 09:47:17.890 ServerApp] Copying unmatched files from /home/adam/Code/tuw/datalab/lab_dir/user1/source/lect1/1 to /home/adam/Code/tuw/datalab/lab_dir/user1/release/lect1/1
[I 2023-07-14 09:47:17.890 ServerApp] Writing 1371 bytes to /home/adam/Code/tuw/datalab/lab_dir/user1/release/lect1/1/gradebook.json
[I 2023-07-14 09:47:17.890 ServerApp] GenerateAssignment conversion done
[I 2023-07-14 09:47:17.890 ServerApp] Reading gradebook file: /home/adam/Code/tuw/datalab/lab_dir/user1/release/lect1/1/gradebook.json
[I 2023-07-14 09:47:17.890 ServerApp] Setting properties of assignment from /home/adam/Code/tuw/datalab/lab_dir/user1/release/lect1/1/gradebook.json
[I 2023-07-14 09:47:17.890 ServerApp] http://127.0.0.1:4010/services/grader/lectures/1/assignments/1/properties
[I 2023-07-14 09:47:17.922 ServerApp] Properties set for assignment
[I 2023-07-14 09:47:17.922 ServerApp] Successfully deleted /home/adam/Code/tuw/datalab/lab_dir/user1/release/lect1/1/gradebook.json
[I 2023-07-14 09:47:17.922 ServerApp] File contents of release: /home/adam/Code/tuw/datalab/lab_dir/user1/release/lect1/1
[I 2023-07-14 09:47:17.922 ServerApp] Untitled.ipynb
[E 2023-07-14 09:47:17.926 ServerApp] Uncaught exception PUT /user/user1/grader_labextension/lectures/1/assignments/1/push/release (::ffff:127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8000', method='PUT', uri='/user/user1/grader_labextension/lectures/1/assignments/1/push/release', version='HTTP/1.1', remote_ip='::ffff:127.0.0.1')
    Traceback (most recent call last):
      File "/home/adam/.local/miniconda3/envs/migration/lib/python3.10/site-packages/tornado/web.py", line 1786, in _execute
        result = await result
      File "/home/adam/Code/tuw/datalab/grader_service/grader_labextension/grader_labextension/handlers/version_control.py", line 384, in put
        git_service.set_author(author=self.user_name)
      File "/home/adam/Code/tuw/datalab/grader_service/grader_labextension/grader_labextension/handlers/base_handler.py", line 80, in user_name
        return self.current_user["name"]
    TypeError: 'JupyterHubUser' object is not subscriptable
[E 2023-07-14 09:47:17.927 ServerApp] {
      "X-Forwarded-Host": "localhost:8000",
      "X-Forwarded-Proto": "http",
      "X-Forwarded-Port": "8000",
      "X-Forwarded-For": "::ffff:127.0.0.1",
      "Content-Length": "0",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Sec-Fetch-Dest": "empty",
      "Cookie": "jupyterhub-user-user1=[secret]; sourcegraphAnonymousUid=[secret]; sourcegraphCohortId=[secret]; sourcegraphDeviceId=[secret]; originalReferrer=[secret]; sourcegraphSourceUrl=[secret]; sourcegraphRecentSourceUrl=[secret]; username-localhost-8888=[secret]; _xsrf=[secret]; jupyterhub-session-id=[secret]",
      "Connection": "close",
      "Dnt": "1",
      "Origin": "http://localhost:8000",
      "Content-Type": "application/json",
      "X-Xsrftoken": "2|e25177fe|e8f61cb6fdc220befaf0b33d3a1d2647|1687504685",
      "Authorization": "token [secret]",
      "Referer": "http://localhost:8000/user/user1/lab/workspaces/auto-t/tree/source/lect1/1",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.5",
      "Accept": "*/*",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/114.0",
      "Host": "localhost:8000"
    }
```

grader service logs:

```conf
INFO     2023-07-14 09:47:17,588 base          | User user1 has been authenticated             (took 5.33ms)
INFO     2023-07-14 09:47:17,612 web           | 200 GET /services/grader/lectures/1 (127.0.0.1) 30.28ms
INFO     2023-07-14 09:47:17,619 base          | User user1 has been authenticated             (took 4.29ms)
INFO     2023-07-14 09:47:17,648 web           | 200 GET /services/grader/lectures/1/assignments/1 (127.0.0.1) 34.27ms
INFO     2023-07-14 09:47:17,897 base          | User user1 has been authenticated             (took 4.90ms)
INFO     2023-07-14 09:47:17,922 web           | 200 PUT /services/grader/lectures/1/assignments/1/properties (127.0.0.1) 30.33ms
```

**Comment by adammccartney** [comment]
note that this issue only seems to exist on the router branch
